### ISSUE TITLE
How to add an onFeatureTapped callback?

### ISSUE THREAD

**Issue by dawid-niedzwiecki** [mapbox/mapbox-maps-flutter#29]
Hi, since I'm migrating from a community driven mapbox package, to this one, I am struggling to find an equivalent for

```

  void _onMapCreated(MapboxMap mapController) {
    this.mapController.onFeatureTapped.add(_onTappedFeature); // this line
  }
  
    Future<void> _onTappedFeature(
    feature,
    Point<double> point,
    LatLng latlng,
  ) async {
  ...
  }

```

What is the equivalent or similar thing for that in the official package?

**Comment by LjubiTech-Maxko** [comment]
Mentioned package handled internally querying rendered features when map was clicked and called the `onFeatureTapped` callback if there were queried features, otherwise it called `onMapClick` callback. For this package we need to do that manually within `onTapListener` callback from `MapWidget`.

Keep in mind that ScreenCoordinate isn't actually screen coordinate but latitude and longitude pair (will be fixed in future releases as I recall from some other issue), and example is using turf library

This can be achieved with the following code example:

```
import 'package:mapbox_maps_flutter/mapbox_maps_flutter.dart';
import 'package:turf/turf.dart' as turf;

// Callback for MapWidget onTapListener
Future<void> onTapListener(ScreenCoordinate coord) async {
    // need to convert coord to real ScreenCoordinate for querying features.
    final ScreenCoordinate conv = await _mapboxMap!.pixelForCoordinate(
      turf.Point(
        coordinates: turf.Position(
          coord.y, coord.x,
        ),
      ).toJson(),
    );

    final List<QueriedFeature?> features = await _mapboxMap!.queryRenderedFeatures(
      RenderedQueryGeometry(
        value: jsonEncode(conv.encode()),
        type: Type.SCREEN_COORDINATE,
      ),
      // add these options if we want to query only specific layer
      RenderedQueryOptions(
        layerIds: ['layer_id_1', 'layer_id_2', ...],
      ),
    );
    
    // do what you need with the features
}
```

**Comment by dawid-niedzwiecki** [comment]
@LjubiTech-Maxko hmm, the previous package gave me a 'feature', which allowed me to know what feature has been tapped. How can I distinguish which one has been tapped?

**Comment by LjubiTech-Maxko** [comment]
Previous package also queried multiple features internally but it selected first feature of the topmost layer and returned it. There were probably more features that were marked as tapped but were filtered out and only 1 was returned. 

You could try adding 2 layers with 2 features at the same coordinates, query the map, and see which one is first and based on that select either first `QueriedFeature` or last.

Yes to both because the return type of the `mapboxMap.queryRenderedFeatures()` is `Future<List<QueriedFeature?>>`

**Comment by dawid-niedzwiecki** [comment]
Thanks for the help!
