### ISSUE TITLE
Custom fonts in symbol layers

### ISSUE THREAD

**Issue by jasperdemmers** [mapbox/mapbox-maps-flutter#771]
I'm using Mapbox Maps Flutter version 2.4.0, which introduces the experimental property `MapboxMap.styleGlyphURL`. This feature allows for applying custom fonts at runtime, including in symbol layers. However, I've encountered an issue where the Euro symbol (€) is not rendered when using a custom font. This appears to be because the glyph range specified (`0-255`) does not include the Euro symbol, which is located at Unicode code point `U+20AC`.

**Steps to Reproduce:**

1. Use `MapboxMap.styleGlyphURL` to apply a custom font with the glyph range `0-255`.
2. Add a symbol layer with text that includes the Euro symbol (€).
3. Observe that the Euro symbol is not rendered.

**Expected Behavior:**

The Euro symbol (€) should be rendered correctly in the symbol layer when using a custom font.

**Actual Behavior:**

The Euro symbol (€) is not visible or rendered in the symbol layer.

**Additional Context:**

- The `text-font` expression for the symbol layer seems to only allow pre-defined fonts, which limits the ability to specify custom glyph ranges.
- The Euro symbol is outside the glyph range `0-255` and requires an extended range, such as `0-767`, to be included.

**Questions:**

- Is there a recommended way to include extended glyph ranges in `mapbox-maps-flutter`?
- Are there plans to enhance the `text-font` expression to support custom fonts more flexibly?

**Environment:**

- Mapbox Maps Flutter version: 2.4.0
- Platform: iOS, Android

**Comment by evil159** [comment]
Hi @jasperdemmers, if the font requesting from the server only contains glyphs for the code points in the range 0–255, it is **not possible** to render the Euro sign (U+20AC) directly with that font, because the Euro sign’s Unicode code point (U+20AC, decimal 8364) lies **outside this range**.

So possible options to render it correctly:
* Switch to fully local glyph rasterization mode, then all glyphs will be rendered with system fonts
* Update the server font to include the Euro sign (U+20AC) by expanding the glyph range to include it. This would require updating the font on the server to support U+20AC.
