### ISSUE TITLE
MapboxMap.getElevation returns null even if coordinate is within the visible region of the screen

### ISSUE THREAD

**Issue by LorenzSchueler** [mapbox/mapbox-maps-flutter#82]
`MapboxMap.getElevation` always returns `null` even if the coordinate is within the visible region of the screen.
Do you have any ideas on how to fix this?

**Comment by LjubiTech-Maxko** [comment]
Elevation data is only available if terrain is enabled for style. But even if you enable terrain there are still some issues regarding the accuracy of the returned elevation. For example, because of the way the terrain raster data is optimized for rendering, different elevations will be returned based on the zoom level. Also, the returned elevation is multiplied with the terrain exaggeration set in the style. 

So, to get the correct elevation you would need to be zoomed in above or at level 14 or 15 because that is the max zoom level at which the data is fully loaded and you would need to know the exaggeration level of the terrain data to divide the returned value with, if it is not 1.

**Comment by LorenzSchueler** [comment]
That makes sense. Thanks for the explanation!!!
Will keep this open until the docs are fixed.
