### ISSUE TITLE
annotation update works after zooming in or out the map

### ISSUE THREAD

**Issue by nnadir35** [mapbox/mapbox-maps-flutter#94]
This is my MapWidget view
```dart

                                            _annoationManager.pointAnnotationManager == null
                                                ? _annoationManager.createMarker(Point(
                                                    coordinates: Position(
                                                      coordinate.y,
                                                      coordinate.x,
                                                    ),
                                                  ))
                                                : _annoationManager.updateMarker(Point(
                                                    coordinates: Position(
                                                      coordinate.y,
                                                      coordinate.x,
                                                    ),
                                                  ));
                                          }
```
here are my fuctions:
```dart
  Future<void> createMarker(Point point) async {
    var imageBytes = (await rootBundle.load('assets/images/locationimage.png')).buffer.asUint8List();
    if (pointAnnotation == null) {
      if (pointAnnotationManager == null) {
        await setPointAnnotationManager();
        pointAnnotationManager!.getIconKeepUpright().then((value) => value = true);
      }
      pointAnnotationManager
          ?.create(PointAnnotationOptions(
              image: imageBytes,
              geometry: point.toJson(),
              textOffset: [0.0, -2.0],
              textColor: Colors.red.value,
              iconSize: 0.04,
              iconOffset: [0.0, -5.0],
              symbolSortKey: 10))
          .then((value) {
        setPointAnnotation = value;
      });
       notifyListeners();
    }
  }

  updateMarker(Point detectedPoint) {
    if (pointAnnotation != null) {
      pointAnnotation?.geometry = detectedPoint.toJson();
      setPointAnnotation = pointAnnotation;
      pointAnnotationManager?.update(pointAnnotation!);
    }
     notifyListeners();
  }

```

I am not able to execute these functions properly. I tap anywhere on the map to create annotation and it works correctly. then update my annotation i touch elsewhere. but as a result anooation goes away then when i zoom in or out the map i see the annation in its new location. How do I fix this problem?

**Comment by cfsbhawkins** [comment]
So I have spent way too much time learning a few tips and tricks here, based off their examples. A few things I have figured out when it comes to annotations. 

You should register your annotation manager during onMapCreate, then your create marker can be called afterwards using a stored ref to the annotation manager.

Depending on how many annotations you want, you might want to look into loading images into styles, and then applying the point annotation to a style, that way your PNG is only loaded once instead of every time, in this case I found it best to create this style on first createMarker call, tried to do it onMapCreate but it was hit or miss the best has been to do it the first time the createMarker is called.

There is another ticket on here that shows a good way to create this style thats completed. Big hint do not use the image library to provide the uint9list, it caused me tons of NPEs only use it for getting the width and height if you don't know it.

**Comment by nnadir35** [comment]
Thanks for your help
